-- Insert batch 7 of courses from Excel spreadsheet
-- Generated on 2025-08-27T18:47:35.240Z
-- Courses 108 to 127

INSERT INTO courses (
  title,
  description,
  short_description,
  category_id,
  status,
  difficulty,
  duration_hours,
  is_public,
  user_id,
  price,
  currency,
  created_at,
  updated_at
) VALUES
(
  'Intro to Literary Theory - 10-12',
  'A survey of the main Eight Literary Theories through one seminal work of literature. ',
  'A survey of the main Eight Literary Theories through one seminal work of literature. ',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Literary Theory - University Students',
  'Literary Theory: A Survey. 10-page Research Paper and 2 5-page essays. ',
  'Literary Theory: A Survey. 10-page Research Paper and 2 5-page essays. ',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Jane Eye - through the lens of THEORY - 10-12',
  'A survey of Literary Theories through Jane Eyre.',
  'A survey of Literary Theories through Jane Eyre.',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Business English I',
  'How to use English in a Business Setting? Resumes, CV’s, Presentations, Email drafting, business proposals. In this important course we equip adults with the right linguistic tools to excel.',
  'How to use English in a Business Setting? Resumes, CV’s, Presentations, Email drafting, business proposals. In this important course we equip adults with t...',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Business English II',
  'How to use English in a Business Setting? Resumes, CV’s, Presentations, Email drafting, business proposals. In this important course we equip adults with the right linguistic tools to excel.',
  'How to use English in a Business Setting? Resumes, CV’s, Presentations, Email drafting, business proposals. In this important course we equip adults with t...',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Business English III ',
  'How to use English in a Business Setting? Resumes, CV’s, Presentations, Email drafting, business proposals. In this important course we equip adults with the right linguistic tools to excel.',
  'How to use English in a Business Setting? Resumes, CV’s, Presentations, Email drafting, business proposals. In this important course we equip adults with t...',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'GPA Management: 5-12',
  'A close support in a 1:1 setting. Through our special attention & careful mentoring, we teach skills of time management, learning discipline, and productivity measurement. ',
  'A close support in a 1:1 setting. Through our special attention & careful mentoring, we teach skills of time management, learning discipline, and productiv...',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Applications to Private School',
  'Applications to Private Schools, selection of the best programs that best fit the student, a careful submission of a perfect application. ',
  'Applications to Private Schools, selection of the best programs that best fit the student, a careful submission of a perfect application. ',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Applications to University ',
  'Applications to Schools, selection of the best programs that best fit the student, a careful submission of a perfect application. ',
  'Applications to Schools, selection of the best programs that best fit the student, a careful submission of a perfect application. ',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Planning ',
  'Learning the very important skills of awareness of one’s work on a weekly basis, paying attention to the details of learning, selecting the right courses and extracurriculars etc.',
  'Learning the very important skills of awareness of one’s work on a weekly basis, paying attention to the details of learning, selecting the right courses a...',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Parental support with Parent/Teacher mtgs',
  'Many parents benefit from additional support navigating their child’s educational life. We support them closely and provide expert mentorship and guidance. ',
  'Many parents benefit from additional support navigating their child’s educational life. We support them closely and provide expert mentorship and guidance....',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Support with email writing and documentation',
  'Expressing oneself professionally and with clarity is difficult. We support our clients with all of their writing needs from the compilation of an email, letter, etc., to getting ready for interviews. ',
  'Expressing oneself professionally and with clarity is difficult. We support our clients with all of their writing needs from the compilation of an email, l...',
  'b24667ac-c601-464f-8420-38156ec85a16',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Support with translation into English',
  'Translation is an art. We support an array of translation needs our clients may have across 6 languages!',
  'Translation is an art. We support an array of translation needs our clients may have across 6 languages!',
  '37b52902-0873-4c16-8428-e4370fe66116',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Translation I - Italian ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught by expert translators and educators. ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught ...',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Translation II - Italian  ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught by expert translators and educators. ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught ...',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Translation III - Italian ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught by expert translators and educators. ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught ...',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Translation I - Latin ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught by expert translators and educators. ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught ...',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Translation II - Latin ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught by expert translators and educators. ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught ...',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Translation III - Latin ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught by expert translators and educators. ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught ...',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
),
(
  'Translation I - German  ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught by expert translators and educators. ',
  'The Art of Translation. Our students will read the work of literature in the Original Language and they will learn valuable Translation Techniques. Taught ...',
  'c199ad8c-b875-4e33-9d3c-47fc82ae7a92',
  'published',
  'standard',
  90,
  true,
  '4ef526fd-43a0-44fd-82e4-2ab404ef673c',
  7000,
  'CAD',
  NOW(),
  NOW()
);
