// Export all relationship components
export { CourseBookManager } from './CourseBookManager'
export { CourseVocabularyManager } from './CourseVocabularyManager'
export { LessonContentManager } from './LessonContentManager'
export { CourseScheduleList } from './CourseScheduleList'
export { CourseLessonManager } from './CourseLessonManager'
export { CourseLessonsWithSchedules } from './CourseLessonsWithSchedules'
export { CourseObjectiveManager } from './CourseObjectiveManager'
export { CourseMethodManager } from './CourseMethodManager'
export { CourseTaskManager } from './CourseTaskManager'
